global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'iprs-svc'
    metrics_path: /svc/iprs/management/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'graphql-server'
    metrics_path: /svc/graphql/management/prometheus
    static_configs:
      - targets: ['host.docker.internal:8082']