version: '3.5'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9098:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - prometheus-vol:/prometheus
      - ./prometheus/configs.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - monitoring


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-vol:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  prometheus-vol:
    driver: local
  grafana-vol:
    driver: local

networks:
  monitoring:
    driver: bridge
    attachable: true