apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
              name: kafka-port
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_BROKER_ID
              value: "1"
#            - name:
#              valueFrom:
#                secretKeyRef:
#                  name:
#                  key:

        - name: zookeeper
          image: bitnami/zookeeper:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
              name: zookeeper-port
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: '2181'
            - name: ALLOW_ANONYMOUS_LOGIN
              value: 'yes'
#            - name: ZOO_SERVERS
#              valueFrom:
#                secretKeyRef:
#                  name:
#                  key:

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  type: NodePort
  ports:
    - port: 2181
      targetPort: 2181
      nodePort: 30002
      protocol: TCP