apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
  labels:
    app: kafka-broker
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
                - name: kafka-broker
                  image: bitnami/kafka:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                    - containerPort: 9092
                      name: kafka-port-1
                    - containerPort: 29092
                      name: kafka-port-2
                  env:
                    - name: KAFKA_ZOOKEEPER_CONNECT
                      value: zookeeper-service:2181
                    - name: KAFKA_BROKER_ID
                      value: "1"
                    - name: KAFKA_ADVERTISED_LISTENERS
                      value: "LISTENER_INTERNAL://kafka-service:29092,LISTENER_EXTERNAL://kafka-service.default.svc.cluster.local:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-service
spec:
  selector:
    app: kafka-broker
  type: ClusterIP
  ports:
    - port: 9092
      name: kafka-port-1
      targetPort: 9092
      protocol: TCP
    - port: 29092
      name: kafka-port-2
      targetPort: 29092
      protocol: TCP
