server:
  port: 8080
  servlet:
    context-path: /svc/graphql

grpc:


spring:
  application:
    name: graphql-server
  data:
    mongodb:
      database: ${spring.application.name}
      uri: ${MONGO_URL:mongodb://localhost:27017}