server:
  port: 8080
  servlet:
    context-path: /svc/graphql

grpc:
  client:
    iprs_svc_client:
      address: ${IPRS_SVC_URL:static://localhost:9090}
      negotiation-type: PLAINTEXT



spring:
  application:
    name: graphql-server
  data:
    mongodb:
      database: ${spring.application.name}
      uri: ${MONGO_URL:mongodb://localhost:27017}