server:
  port: 8080
  servlet:
    context-path: /svc/iprs

grpc:
  server:
    port: 9090

spring:
  application:
    name: iprs-app
  data:
    mongodb:
      database: ${spring.application.name}
      uri: ${MONGO_URL:mongodb://localhost:27017}