server:
  port: 8080
  servlet:
    context-path: /svc/iprs

grpc:
  server:
    port: 9191

spring:
  application:
    name: iprs-app
  # Temporal configurations
  temporal:
    connection:
      target: localhost:7233
    workers-auto-discovery:
      packages: dev.njari
    start-workers: true
    namespace: default
  data:
    mongodb:
      database: ${spring.application.name}
      uri: ${MONGO_URL:mongodb://localhost:27017}

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'


