apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-server
  labels:
    app: graphql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-server
  template:
    metadata:
      labels:
        app: graphql-server
    spec:
      containers:
      - name: graphql-server
        image: graphql-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http-port

---
apiVersion: v1
kind: Service
metadata:
  name: graphql-server-np
spec:
  selector:
    app: graphql-server
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 31006
